"""update user model

Revision ID: b0e05364c928
Revises: 06cf89e43b4a
Create Date: 2024-07-27 12:04:59.174100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e05364c928'
down_revision: Union[str, None] = '06cf89e43b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['uid'])
    op.drop_column('users', 'transaction_limit')
    op.drop_column('users', 'cloud_name')
    op.drop_column('users', 'endpoint')
    op.drop_column('users', 'storage_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('cloud_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('transaction_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
