"""add cloudnameto users

Revision ID: d68773574b84
Revises: b0e05364c928
Create Date: 2024-07-31 14:42:55.485201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d68773574b84"
down_revision: Union[str, None] = "b0e05364c928"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("cloudname", sa.String(), nullable=False, server_default="inteliver"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cloudname")
    # ### end Alembic commands ###
