SECRET_KEY = "your_secret_key"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30 * 24 * 60  # 1 month
RESET_PASSWORD_TOKEN_EXPIRE_MINUTES = 60  # 1 hour
EMAIL_VALIDATION_TOKEN_EXPIRE_MINUTES = 60  # 1 hour
